import type { EventInput } from "@fullcalendar/core";

export const CALENDAR_EVENTS: EventInput[] = [
  {
    id: "b1",
    title: "Stormy +1 - Marina Loft 2B",
    start: "2026-07-01",
    end: "2026-07-03",
    allDay: true,
    classNames: ["evt-booking", "evt-neutral"],
  },
  {
    id: "b2",
    title: "Michele +1 - Dolores Duplex1",
    start: "2026-07-05",
    end: "2026-07-10",
    allDay: true,
    classNames: ["evt-booking", "evt-green"],
  },
  {
    id: "b3",
    title: "Kieanna +1 - Juniper Flats 4A",
    start: "2026-07-10",
    end: "2026-07-12",
    allDay: true,
    classNames: ["evt-booking", "evt-amber"],
  },
  {
    id: "b4",
    title: "Mercy +2 - Marina Loft 2B",
    start: "2026-07-09",
    end: "2026-07-13",
    allDay: true,
    classNames: ["evt-booking", "evt-blue"],
  },
  {
    id: "b5",
    title: "Ravi +3 - Alder House",
    start: "2026-07-13",
    end: "2026-07-18",
    allDay: true,
    classNames: ["evt-booking", "evt-blue"],
  },
  {
    id: "b6",
    title: "Harold +1 - Fern Grove Studio",
    start: "2026-07-15",
    end: "2026-07-19",
    allDay: true,
    classNames: ["evt-booking", "evt-blue"],
  },
  {
    id: "b7",
    title: "Ava +4 - Dolores Duplex",
    start: "2026-07-25",
    end: "2026-07-29",
    allDay: true,
    classNames: ["evt-booking", "evt-amber"],
  },
  {
    id: "c1",
    title: "Clean - Rosa 11:00",
    start: "2026-07-06",
    allDay: true,
    classNames: ["evt-cleaning"],
  },
  {
    id: "c2",
    title: "Clean - Priya 12:30",
    start: "2026-07-08",
    allDay: true,
    classNames: ["evt-cleaning"],
  },
  {
    id: "c3",
    title: "Clean - Ken 11:30",
    start: "2026-07-09",
    allDay: true,
    classNames: ["evt-cleaning"],
  },
  {
    id: "c4",
    title: "Clean - Marta 11:00",
    start: "2026-07-22",
    allDay: true,
    classNames: ["evt-cleaning"],
  },
];
