ALTER TABLE "client_profiles"
  ADD COLUMN IF NOT EXISTS "companyName" TEXT,
  ADD COLUMN IF NOT EXISTS "primaryContact" TEXT,
  ADD COLUMN IF NOT EXISTS "portfolioSize" INTEGER,
  ADD COLUMN IF NOT EXISTS "timezone" TEXT;

ALTER TABLE "cleaner_profiles"
  ADD COLUMN IF NOT EXISTS "serviceArea" TEXT,
  ADD COLUMN IF NOT EXISTS "hourlyRate" INTEGER,
  ADD COLUMN IF NOT EXISTS "availability" TEXT,
  ADD COLUMN IF NOT EXISTS "rating" DECIMAL(4,2);
