import path from "node:path";
import type { AgentConfig } from "../providers/types.js";
import { getTaskProvider } from "../providers/registry.js";
import type { GitHubIssue } from "../github/types.js";
import { GitHubClient } from "../github/client.js";
import { CodebaseReader } from "../codebase/reader.js";
import { PlaywrightRunner } from "../test_runner/playwright.js";
import { formatTestReport } from "../test_runner/reporter.js";
import { GitBranch } from "../github/git_operations.js";
import { buildIssueContext, determineBaseBranch } from "../utils/issue_context_builder.js";
import { runAgentLoop } from "../agent/Agent_Runner_Engine.js";
import { generateTests } from "../agent/Agent_Tests_Generator.js";
import { runTests } from "../test_runner/run_tests.js";
import { generateTestReport } from "../agent/Agent_Tests_Report_Generator.js";
import { reviewTests } from "../agent/Agent_Tests_Reviewer.js";
import { autoCommit } from "../github/auto_commit.js";
import { summarizeResults } from "../agent/Agent_Summarize.js";
import { SYSTEM_PROMPTS } from "../prompts/index.js";
import type { TaskResult } from "../utils/types.js";
import { runTestsLoop } from "../utils/test_pipeline.js";
import { logger } from "../utils/logger.js";

export interface OrchestratorConfig {
  agentConfig: AgentConfig;
  githubClient: GitHubClient;
  mcalendarPath: string;
  testProjectPath: string;
  maxRetries: number;
}

export async function processIssue(
  issue: GitHubIssue,
  config: OrchestratorConfig
): Promise<TaskResult> {
  const { agentConfig, githubClient, mcalendarPath, testProjectPath, maxRetries } = config;
  const reader = new CodebaseReader(mcalendarPath);
  const testReader = new CodebaseReader(testProjectPath);
  const runner = new PlaywrightRunner(testProjectPath);
  const git = new GitBranch(mcalendarPath);

  const testOutputPath = path.join(testProjectPath, "tests", "e2e");

  logger.info(`Fetching issue #${issue.number}: ${issue.title}`);

  const defaultBranch = await githubClient.getDefaultBranch();
  //const baseBranch = determineBaseBranch(issue, defaultBranch);
  // Added this code for Debug Purpose
  const baseBranch = "main-agentic-ai"; // For now, always use the default branch
  const branchName = GitBranch.branchName(issue.number, issue.title);

  logger.info(`Base branch: ${baseBranch}`);
  logger.info(`Creating branch: ${branchName}`);

  await git.createAndCheckout(branchName, baseBranch);

  const issueContext = buildIssueContext(issue, reader);

  // Step 1: Analyze issue
  const analysis = await runAgentLoop(
    {
      provider: getTaskProvider("Agent_Issue_Analyzer", agentConfig),
      reader,
      runner,
      testOutputPath,
      mcalendarPath,
      maxTokens: agentConfig["Agent_Issue_Analyzer"]?.maxTokens,
      temperature: agentConfig["Agent_Issue_Analyzer"]?.temperature,
    },
    SYSTEM_PROMPTS.Agent_Issue_Analyzer,
    `Analyze this issue and determine what E2E tests need to be written:\n\n${issueContext}`
  );

  logger.success("Analysis complete");

  // Step 2: Generate tests
  const testFilename = `issue-${issue.number}-${GitBranch.slugify(issue.title)}.spec.ts`;

  await generateTests(
    agentConfig,
    reader,
    runner,
    testOutputPath,
    mcalendarPath,
    `Generate a Playwright E2E test file for this issue.\n\nFilename: ${testFilename}\n\nAnalysis:\n${analysis}\n\nIssue Context:\n${issueContext}\n\nIMPORTANT: Use the write_test_file tool to save the test as "${testFilename}".`
  );

  // Step 3: Run tests + Review/fix loop
  const { testResult, retries } = await runTestsLoop({
    maxRetries,
    testFilename,
    runTests: () => runTests(runner, testFilename),
    reviewTests: (testContent, errorContext) =>
      reviewTests(
        agentConfig,
        reader,
        runner,
        testOutputPath,
        mcalendarPath,
        testFilename,
        testContent,
        `Fix the failing test. Here are the errors:\n\n${errorContext}`
      ),
    readTestContent: () => testReader.readFile(testFilename),
  });

  // Step 4: Generate report
  const report = await generateTestReport(agentConfig, reader, runner, testOutputPath, mcalendarPath, testResult);

  // Step 5: Commit + Push + PR
  const commitResult = await autoCommit(
    git,
    githubClient,
    branchName,
    baseBranch,
    `test: auto-generated E2E tests for issue #${issue.number}`,
    `test: E2E tests for issue #${issue.number}`,
    `## Automated Test Generation\n\n**Issue:** #${issue.number} — ${issue.title}\n\n### Test Results\n${formatTestReport(testResult)}\n\n### Files Changed\n- \`tests/e2e/${testFilename}\` (new)\n\n### How to Run\n\`\`\`bash\nnpx playwright test tests/e2e/${testFilename}\n\`\`\`\n\n---\n*Generated by MCalendar Test Agent*`
  );

  // Step 6: Summarize
  const comment = await summarizeResults(
    agentConfig,
    reader,
    runner,
    testOutputPath,
    mcalendarPath,
    `Summarize these test results for a GitHub comment:\n\nIssue: #${issue.number} — ${issue.title}\nBranch: ${branchName}\nPR: #${commitResult.prNumber}\nTest file: ${testFilename}\n\nTest Results:\n${formatTestReport(testResult)}\n\nReport:\n${report}`
  );

  await githubClient.addComment(issue.number, comment);

  logger.success(`Issue #${issue.number} complete — PR #${commitResult.prNumber}, ${testResult.passed} passed, ${testResult.failed} failed`);

  return {
    success: testResult.success,
    output: `PR #${commitResult.prNumber} created with ${testResult.passed} tests passed`,
    filesWritten: [testFilename],
    testsPassed: testResult.passed,
    testsFailed: testResult.failed,
    retries,
  };
}
